### ISSUE TITLE
Version 4.0.0 is not working

### ISSUE THREAD

**Issue by Marcoral** [goxr3plus/FX-BorderlessScene#14]
While being created, BorderlessScene requires some FXML files, which had been removed in following commit:
[https://github.com/goxr3plus/FX-BorderlessScene/commit/0a1eb8391568ad23ecc9be9493b3a3efa9196b41](url)

As a result, if you invoke constructor of a BorderlessScene, you'll get "java.lang.IllegalStateException: Location is not set."

**Comment by goxr3plus** [comment]
Please clone the latest code, i have tested it locally and it works, i repackaged everything. 

I used it also with XR3Player and it works. Let me know if the error is still there for you.

**Comment by Marcoral** [comment]
Do I have to build the solution in some specific way?
I run it as an Eclipse "Java project" and, as I mentioned, FXMLLoader refers files such as Borderless.fxml, but project does not have such files at all (you removed them in commit 0a1eb8391568ad23ecc9be9493b3a3efa9196b41)

And, if you restore old resources, you'll get another exception:

> javafx.fxml.LoadException: Root value already specified.

whole stacktrace:

> `at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2597)
	at javafx.fxml.FXMLLoader.createElement(FXMLLoader.java:2755)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2704)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at com.goxr3plus.fxborderlessscene.borderless.BorderlessPane.<init>(BorderlessPane.java:39)
	at com.goxr3plus.fxborderlessscene.borderless.BorderlessScene.<init>(BorderlessScene.java:55)
	at com.goxr3plus.fxborderlessscene.borderless.BorderlessScene.<init>(BorderlessScene.java:90)
	at com.goxr3plus.fxborderlessscene.application.Main.start(Main.java:27)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)`

This is obviously because old files indeed already contained root and controller.
I think you just might not commited new version of these files, if ones exist.

I am stuck in this point, because my project also depends on your library.

**Comment by goxr3plus** [comment]
Ouhh i am sorry i see the files are missing too, i am opening the computer now, omg how i forgot to add them again....

**Comment by goxr3plus** [comment]
I will make a new release right now.

**Comment by goxr3plus** [comment]
Ready :) https://github.com/goxr3plus/FX-BorderlessScene/releases/tag/4.1.0 let me know

**Comment by Marcoral** [comment]
Yep, everything works now. BTW: I love new look of example app. Keep up good work!
When I find some time, I'll try to help you with [Aero Snap screen corners issue](https://github.com/goxr3plus/FX-BorderlessScene/issues/7).

**Comment by goxr3plus** [comment]
THANK YOUUUUUUU :) I really like Graphic Designing
